export enum InboxCategory {
  BOARD = "BOARD",
  TRANSFER = "TRANSFER",
  PLAYER = "PLAYER",
  STAFF = "STAFF",
  COMPETITION = "COMPETITION",
  FIXTURE = "FIXTURE",
  TRAINING = "TRAINING",
  FINANCE = "FINANCE",
  INJURY = "INJURY",
  YOUTH = "YOUTH",
  MEDIA = "MEDIA",
  INTERNATIONAL = "INTERNATIONAL",
}

export enum InboxPriority {
  LOW = "LOW",
  NORMAL = "NORMAL",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum InboxActionType {
  NONE = "NONE",

  VIEW_PLAYER = "VIEW_PLAYER",
  VIEW_CLUB = "VIEW_CLUB",
  VIEW_MATCH = "VIEW_MATCH",
  VIEW_TRANSFER = "VIEW_TRANSFER",
  VIEW_COMPETITION = "VIEW_COMPETITION",
  VIEW_BOARD = "VIEW_BOARD",
  VIEW_FINANCES = "VIEW_FINANCES",
  VIEW_STAFF = "VIEW_STAFF",
  VIEW_YOUTH = "VIEW_YOUTH",
  VIEW_TRAINING = "VIEW_TRAINING",
}