export enum TransactionType {
  MATCHDAY_REVENUE = "MATCHDAY_REVENUE",

  TV_REVENUE = "TV_REVENUE",

  SPONSORSHIP = "SPONSORSHIP",

  PRIZE_MONEY = "PRIZE_MONEY",

  PLAYER_SALE = "PLAYER_SALE",

  PLAYER_PURCHASE = "PLAYER_PURCHASE",

  PLAYER_WAGES = "PLAYER_WAGES",

  STAFF_WAGES = "STAFF_WAGES",

  TRANSFER_INSTALLMENT = "TRANSFER_INSTALLMENT",

  STADIUM_MAINTENANCE = "STADIUM_MAINTENANCE",

  STADIUM_PROJECT = "STADIUM_PROJECT",

  OWNER_INVESTMENT = "OWNER_INVESTMENT",

  FFP_FINE = "FFP_FINE",

  OTHER = "OTHER"
}